# Generated by Django 5.2.6 on 2025-09-19 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Category', models.CharField(blank=True, choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('others', 'Others')], max_length=20)),
                ('Subcategory', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('trainee', 'Trainee'), ('grey_Shirt', 'Grey Shirt'), ('safety_shoes(gents)', 'Safety Shoes (Gents)'), ('safety_shoes(ladies)', 'Safety Shoes (Ladies)'), ('grey(gents)', 'Grey (Gents)'), ('grey(ladies)', 'Grey (Ladies)'), ('white(gents)', 'White (Gents)'), ('white(ladies)', 'White (Ladies)'), ('normal', 'Normal'), ('overhead', 'Overhead')], max_length=50)),
                ('size', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=20)),
                ('Issued_quantity', models.PositiveIntegerField(default=0)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('Next_issue_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('others', 'Others')], max_length=20)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('trainee', 'Trainee'), ('grey_Shirt', 'Grey Shirt'), ('safety_shoes(gents)', 'Safety Shoes (Gents)'), ('safety_shoes(ladies)', 'Safety Shoes (Ladies)'), ('grey(gents)', 'Grey (Gents)'), ('grey(ladies)', 'Grey (Ladies)'), ('white(gents)', 'White (Gents)'), ('white(ladies)', 'White (Ladies)'), ('normal', 'Normal'), ('overhead', 'Overhead')], max_length=20)),
                ('size', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=20)),
            ],
        ),
    ]
