# Generated by Django 5.2.6 on 2025-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_employeeissue_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeissue',
            name='Category',
            field=models.CharField(blank=True, choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('trainee', 'Trainee'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('trainee', 'Trainee'), ('others', 'Others')], max_length=20),
        ),
    ]
