# Generated by Django 5.2.6 on 2025-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_employeeissue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeissue',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
