# Generated by Django 5.2.6 on 2025-09-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_employeeissue_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeissue',
            name='gender',
        ),
    ]
