# Generated by Django 5.2.6 on 2025-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_employeeissue_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeissue',
            name='Buy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
