# Generated by Django 5.2.6 on 2025-10-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_employeeissue_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeissue',
            name='Buy',
        ),
    ]
