# Generated by Django 5.2.6 on 2025-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_employeeissue_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeissue',
            name='Buy',
            field=models.CharField(blank=True, choices=[('in', 'In Stock'), ('out', 'Out of Stock'), ('low', 'Low Stock')], max_length=20),
        ),
    ]
