# Generated by Django 5.2.6 on 2025-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_employeeissue_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeissue',
            name='Buy',
            field=models.CharField(blank=True, choices=[('in', 'In Stock'), ('out', 'Out of Stock'), ('low', 'Low Stock'), ('extra', 'Extra / Buy')], max_length=20),
        ),
    ]
