# Generated by Django 5.2.6 on 2025-10-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_location_employeedetails_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='entity',
            field=models.CharField(blank=True, choices=[(' A SEZ(AEQUS SEZ PRIVATE LIMITED)', ' A SEZ(AEQUS SEZ PRIVATE LIMITED)'), ('AEPPL(AEQUS ENGINEERED PLASTICS PRIVATE LIMITED)', 'AEPPL(AEQUS ENGINEERED PLASTICS PRIVATE LIMITED)'), ('AAPL(AEQUS AUTOMOTIVE PRIVATE LIMITED)', 'AAPL(AEQUS AUTOMOTIVE PRIVATE LIMITED)'), ('API(AEROSPACE PROCESSING INDIA PVT. LTD.)', 'API(AEROSPACE PROCESSING INDIA PVT. LTD.)'), ('ASMIPL-I,II,III(AEROSTRUCTURES MANUFACTURING INDIA PRIVATE LIMITED)', 'ASMIPL-I,II,III(AEROSTRUCTURES MANUFACTURING INDIA PRIVATE LIMITED)'), ('SFIPL(SQUAD FORGING INDIA PRIVATE LIMITED)', 'SFIPL(SQUAD FORGING INDIA PRIVATE LIMITED)'), ('APL-SS , II, IV (AEQUS PRIVATE LIMITED)', 'APL-SS , II, IV (AEQUS PRIVATE LIMITED)'), (' AAI(AEROSTRUCTURES ASSEMBLIES INDIA PVT. LTD)', ' AAI(AEROSTRUCTURES ASSEMBLIES INDIA PVT. LTD)'), ('AFCPPL(Aequs Force consumer Product Private Limited )', 'AFCPPL(Aequs Force consumer Product Private Limited )')], max_length=100),
        ),
    ]
