# Generated by Django 5.2.6 on 2025-10-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventory_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeissue',
            name='Category',
            field=models.CharField(blank=True, choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('trainee', 'Trainee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeissue',
            name='Subcategory',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('trainee', 'Trainee'), ('jeans', 'Jeans'), ('ladies', 'Ladies'), ('gents', 'Gents'), ('Grey_Shirt', 'Grey Shirt'), ('White_Shirt', 'White Shirt'), ('normal', 'Normal'), ('overhead', 'Overhead')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeissue',
            name='size',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('overhead', 'Overhead'), ('normal', 'Normal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('trainee', 'Trainee'), ('jeans', 'Jeans'), ('ladies', 'Ladies'), ('gents', 'Gents'), ('Grey_Shirt', 'Grey Shirt'), ('White_Shirt', 'White Shirt'), ('normal', 'Normal'), ('overhead', 'Overhead')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles'), ('trainee', 'Trainee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('overhead', 'Overhead'), ('normal', 'Normal')], max_length=20),
        ),
    ]
