# Generated by Django 5.2.6 on 2025-10-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_entity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.AddField(
            model_name='employeeissue',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='inventory.employeedetails'),
        ),
    ]
