# Generated by Django 5.2.6 on 2025-10-16 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_entity_employeeissue_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeissue',
            name='Category',
            field=models.CharField(blank=True, choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('formals', 'Formals'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('safety_shoes', 'Safety_Shoes'), ('goggles', 'Goggles')], max_length=20),
        ),
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stationarytype')),
            ],
        ),
    ]
