# Generated by Django 5.2.6 on 2025-10-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stationarytype_alter_employeeissue_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stationary',
        ),
        migrations.DeleteModel(
            name='StationaryType',
        ),
    ]
