# Generated by Django 5.2.6 on 2025-10-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_employeedetails_entity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='Location',
        ),
    ]
