# Generated by Django 5.2.6 on 2025-10-25 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_location_location_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationaryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationary_issues', to='inventory.employeedetails')),
                ('stationary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stationarytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
