# Generated by Django 5.2.6 on 2025-10-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stationaryissue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationaryIssue',
        ),
    ]
