# Generated by Django 5.2.6 on 2025-10-25 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_delete_stationaryissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationaryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employeedetails')),
                ('stationary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stationary')),
            ],
        ),
    ]
