# Generated by Django 5.2.5 on 2025-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_stationaryissue_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeissue',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price paid if item was bought', max_digits=10, null=True),
        ),
    ]
